---
- name: Start openslides service
  sudo: yes
  sudo_user: root
  service:
    name: 'openslides_instance_{{ openslides_instance_id }}.service'
    enabled: yes

- name: Deactivate openslides proxy service
  sudo: yes
  sudo_user: root
  service:
    name: 'openslides_instance_proxy_{{ openslides_instance_id }}.service'
    enabled: yes
    state: stopped

- name: Deactivate openslides proxy socket
  sudo: yes
  sudo_user: root
  service:
    name: 'openslides_instance_proxy_{{ openslides_instance_id }}.socket'
    enabled: yes
    state: started

- name: Create 502.html
  template:
    dest: "{{ openslides_instance_path }}/502.html"
    src: 502.html.j2
