---
- name: Stop and enalbe openslides
  sudo: yes
  sudo_user: root
  service:
    name: openslides_instance_{{ openslides_instance_id }}.service
    enabled: no
    state: stopped

- name: Stop and enalbe openslides
  sudo: yes
  sudo_user: root
  service:
    name: openslides_instance_proxy_{{ openslides_instance_id }}.service
    enabled: no
    state: stopped

- name: Stop and enalbe nginx via socket activation
  sudo: yes
  sudo_user: root
  service:
    name: openslides_instance_proxy_{{ openslides_instance_id }}.socket
    enabled: no
    state: stopped

- name: Remove systemd units for openslides
  sudo: yes
  sudo_user: root
  file: path=/etc/systemd/system/{{ openslides_instance_service_name }}.service state=absent

- name: Remove systemd units for openslides
  sudo: yes
  sudo_user: root
  file: path=/etc/systemd/system/openslides_instance_proxy_{{ openslides_instance_id }}.service state=absent

- name: Remove openslides proxy service unit for socket activation
  sudo: yes
  sudo_user: root
  file: path=/etc/systemd/system/openslides_instance_proxy_{{ openslides_instance_id }}.socket state=absent

- name: Remove nginx location config
  when: "'{{ openslides_instance_mode }}' == 'path'"
  sudo: yes
  sudo_user: root
  file: path=/etc/nginx/openslides/openslides_{{ openslides_instance_id }}.locations state=absent

- name: Remove nginx vhost config
  when: "'{{ openslides_instance_mode }}' == 'subdomain'"
  sudo: yes
  sudo_user: root
  file: path=/etc/nginx/openslides/openslides_{{ openslides_instance_id }}.conf state=absent

- name: Reload systemd units
  sudo: yes
  sudo_user: root
  command: systemctl daemon-reload
