---
- name: Creates directory
  file: path="{{ openslides_instance_path }}" state=directory

- name: Creates data directory
  file: path="{{ openslides_instance_path }}/data" state=directory

- set_fact:
    setting_db_template: "settings_db_{{ openslides_instance_db }}.j2"

- name: Create Settings
  template:
    dest: "{{ openslides_instance_path }}/settings.py"
    src: settings.py.j2

- name: Create supervisor configuration
  template:
    dest: "{{ openslides_instance_path }}/supervisord.conf"
    src: supervisord.conf.j2

- name: Create 502.html
  template:
    dest: "{{ openslides_instance_path }}/502.html"
    src: 502.html.j2

- set_fact:
    openslides_rkt_base: /usr/bin/rkt run
      --uuid-file-save={{ openslides_instance_path }}/rkt-uuid
      --port=8000-tcp:{{ openslides_instance_port }}
      --set-env=PYTHONPATH=/data:/app
      --volume volume-data,kind=host,source={{ openslides_instance_path }},readOnly=false
      --volume volume-supervisord-conf,kind=host,source={{ openslides_instance_path }}/supervisord.conf {{ openslides_instance_image }}
      --user={{ openslides_uid }}
      --group={{ openslides_gid }}
      --exec supervisord -- -c /supervisord.conf

