---

- getent: database=passwd

- name: Check variable openslides_secure_key
  when: not openslides_secure_key
  fail:
    msg: The variable openslides_secure_key is not set.

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- set_fact:
    username_on_the_host: "{{username_on_the_host.stdout}}"

- set_fact:
    openslides_uid: "{{ getent_passwd[username_on_the_host][1] }}"
    openslides_gid: "{{ getent_passwd[username_on_the_host][2] }}"

- name: Create nginx configuration
  include: create_nginx_conf.yml

- name: Create instance container
  include: create_container.yml

- name: Create systemd units
  include: create_units.yml

- name: Initialize database
  include: init_instance_database.yml

- stat: path={{ openslides_instance_path }}/static
  register: static_path

- name: Collect static
  sudo: yes
  when: static_path.stat.exists == False
  sudo_user: root
  command: '{{ openslides_rkt_manage }} collectstatic --noinput'
